// This file has been generated by Specta. Do not edit this file manually.
/**  The exact action an approval permits. Kept after retention cleanup. */
export type Action = {
	/**  What the requester will do, such as `merge`. */
	verb: string,
	/**  What it will do it to, such as `pr:origin89hq/engineering#25`. */
	target: string,
	/**
	 *  The full revision the approval is bound to: a 40- or 64-character
	 *  lowercase hex git object id.
	 */
	rev: string,
	/**  Constraints the requester commits to, such as "squash merge into main". */
	limits?: string | null,
};

/**  A person's answer. Immutable once recorded. */
export type Answer = {
	/**
	 *  The chosen option's id, or `_custom` when the responder wrote their own
	 *  reply in `input` instead of choosing an option.
	 */
	optionId: string,
	/**  The chosen option's label at answer time. */
	optionLabel: string,
	/**  What the answer means. */
	decision: Decision,
	/**  Free-text instructions from the responder. */
	input: string | null,
	/**  The action the answer applies to, copied from the Ask. */
	action: Action | null,
	/**  GitHub login of the responder at answer time. */
	responder: string,
	/**  Numeric GitHub user id of the responder. */
	responderId: number,
	/**  Whether a passkey assertion was verified for this answer. */
	passkey: boolean,
	/**  When the answer was recorded. */
	answeredAt: number,
};

/**  Body of `POST /v1/asks/{id}/trace`. */
export type AppendTrace = {
	/**  What happened. */
	event: ReportedEvent,
	/**  References such as `orca.run=r_81`. Stored and linked, never contacted. */
	refs?: { [key in string]: string },
	/**  Evidence link. Required for `applied` and `failed`. */
	url?: string | null,
	/**  Short explanation. Required for `failed`. */
	note?: string | null,
};

/**  An Ask as the API returns it. */
export type Ask = {
	/**  ULID. */
	id: string,
	/**  Name of the requester that created it. */
	requester: string,
	/**  GitHub login of the only person who can answer it. */
	to: string,
	/**  GitHub repository the Ask concerns, as `owner/name`. Kept after retention. */
	repo: string | null,
	/**  The decision it asks about. */
	decisionKey: string,
	/**  The Ask this one replaced. */
	supersedes: string | null,
	/**  The Ask that replaced this one. */
	supersededBy: string | null,
	/**  What the requester needs. */
	kind: Kind,
	/**  How quickly a person should see it. */
	urgency: Urgency,
	/**  What a wrong answer can cost. */
	risk: Risk,
	/**  One line. */
	title: string,
	/**  Markdown. `null` after retention cleanup. */
	body: string | null,
	/**  Empty after retention cleanup. */
	links: Link[],
	/**  The exact action an approval permits. */
	action: Action | null,
	/**  The answers offered. */
	options: AskOption[],
	/**  Context for resuming work. */
	resume: Resume | null,
	/**  When it expires unanswered. */
	expiresAt: number | null,
	/**  Lifecycle state. */
	state: AskState,
	/**  When it was created. */
	createdAt: number,
	/**  When it left `open`. */
	closedAt: number | null,
	/**  Present once answered. */
	answer: Answer | null,
	/**  What happened after the answer, oldest first. */
	trace: TraceEntry[],
};

/**  Response of `GET /v1/asks`. */
export type AskList = {
	/**  Oldest first. */
	asks: Ask[],
	/**  Pass as `after` to read the next page; `null` on the last page. */
	next: string | null,
};

/**  An answer the requester offers. */
export type AskOption = {
	/**  Stable id, unique within the Ask. */
	id: string,
	/**  Text on the button. */
	label: string,
	/**  What choosing this option means. */
	decision: Decision,
	/**  Whether the responder must write instructions with this option. */
	inputRequired?: boolean,
};

/**  Lifecycle state. Every state other than `open` is terminal. */
export type AskState = 
/**  Waiting for a person. */
"open" | 
/**  A person chose an option. */
"answered" | 
/**  Nobody answered before `expiresAt`. Carries no decision. */
"expired" | 
/**  The requester no longer needs an answer. */
"withdrawn" | 
/**  The requester replaced it with a newer Ask for the same decision key. */
"superseded";

/**  Body of `POST /v1/asks`. */
export type CreateAsk = {
	/**
	 *  Unique per requester. Repeating a create with the same key and content
	 *  returns the existing Ask; different content is a conflict.
	 */
	idemKey: string,
	/**  Names the decision. At most one open Ask per requester and decision key. */
	decisionKey: string,
	/**
	 *  GitHub login of the person who should answer. They must have signed in
	 *  to Roger once. Absent means the person who created the requester.
	 */
	to?: string | null,
	/**
	 *  GitHub repository the Ask concerns, as `owner/name`. The CLI fills it
	 *  from the checkout's `origin` remote when not given.
	 */
	repo?: string | null,
	/**  The open Ask, with the same decision key, that this one replaces. */
	supersedes?: string | null,
	/**  What the requester needs. */
	kind: Kind,
	/**  How quickly a person should see it. */
	urgency: Urgency,
	/**  What a wrong answer can cost. */
	risk: Risk,
	/**  One line. */
	title: string,
	/**  Markdown. */
	body?: string | null,
	/**  Links shown with the Ask. */
	links?: Link[],
	/**  Required for `approval`. */
	action?: Action | null,
	/**  The answers offered. */
	options: AskOption[],
	/**  Context for resuming work after the answer. */
	resume?: Resume | null,
	/**  Working minutes until the Ask expires unanswered. Absent means never. */
	expiresInMinutes?: number | null,
};

/**  What an option means. Scripts branch on this, never on option order. */
export type Decision = 
/**  Permits the Ask's action. Only `approval` Asks offer it. */
"approve" | 
/**  Refuses the Ask's action. */
"reject" | 
/**  Anything else, such as "fix" with instructions. */
"other";

/**  Body of every error response. */
export type ErrorBody = {
	/**  What went wrong. */
	error: ErrorDetail,
};

/**  Machine-readable error category. */
export type ErrorCode = 
/**  The request is malformed or breaks a content rule. */
"invalid_request" | 
/**  Missing, unknown, or revoked credentials. */
"unauthorized" | 
/**  The credentials cannot perform this operation. */
"forbidden" | 
/**  No such Ask, or it belongs to another requester. */
"not_found" | 
/**  The Ask is no longer open, or the request conflicts with existing state. */
"conflict" | 
/**  The request body exceeds the size limit. */
"too_large" | 
/**  Too many attempts; wait and try again. */
"too_many_requests" | 
/**  The Worker failed. */
"internal";

/**  Details of a failed request. */
export type ErrorDetail = {
	/**  Category. */
	code: ErrorCode,
	/**  Human-readable explanation. */
	message: string,
	/**  The Ask's current state, on conflicts about an Ask. */
	state: AskState | null,
};

/**  Response of `GET /v1/events`. */
export type EventList = {
	/**  Oldest first. */
	events: StateChange[],
	/**  Pass as `after` to continue; equals the request's `after` when empty. */
	next: number,
};

/**  What the requester needs from a person. */
export type Kind = 
/**  May the requester perform this exact action? */
"approval" | 
/**  The requester is stuck and needs a choice or instruction. */
"question" | 
/**  No answer needed, only acknowledgement. */
"fyi";

/**  A labelled link shown with the Ask. Purged by retention. */
export type Link = {
	/**  Short label, such as `PR`. */
	label: string,
	/**  An `https` URL. */
	url: string,
};

/**  Response of `GET /v1/login`: how `roger login` signs in with GitHub. */
export type LoginConfig = {
	/**  The deployment's GitHub OAuth app, for GitHub's device flow. */
	githubClientId: string,
	/**  OAuth scopes to request; the Worker needs them to check membership. */
	scope: string,
};

/**  Body of `POST /v1/login`. */
export type MachineLogin = {
	/**
	 *  A GitHub token from the device flow. The Worker checks who it belongs
	 *  to, revokes it, and never stores it.
	 */
	githubToken: string,
	/**  The machine name, such as `studio`. */
	machine: string,
};

/**  Response of `POST /v1/login`. */
export type MachineToken = {
	/**  The machine credential. Shown once; the Worker stores only its hash. */
	credential: string,
	/**  The machine name. */
	machine: string,
	/**  GitHub login of the person who logged in, who owns the machine. */
	owner: string,
};

/**  A trace event the requester may report. `delivered` is Roger's own. */
export type ReportedEvent = 
/**  The requester started work because of the answer. */
"dispatched" | 
/**  A step worth showing, such as a push. */
"progress" | 
/**  The requester acted on the answer. Terminal; needs a `url`. */
"applied" | 
/**  The requester tried and failed. Terminal; needs a `url` and a `note`. */
"failed" | 
/**  The answer no longer applies. Terminal. */
"not_applicable" | 
/**
 *  Replaces a wrong evidence link on the terminal event; needs a `url`
 *  and a `note` saying what was wrong.
 */
"corrected";

/**  What a fresh worker needs to continue after the answer arrives. */
export type Resume = {
	/**  Orca Run id. */
	run?: string | null,
	/**  Orca Task id. */
	task?: string | null,
	/**  Branch the work continues on. */
	branch?: string | null,
	/**  Head revision when the Ask was created. */
	rev?: string | null,
};

/**  What can go wrong if the answer is wrong. Decides presentation. */
export type Risk = 
/**  For example, merging a green PR in a web repository. */
"routine" | 
/**  Secrets, spending, authorization, or data-loss changes. */
"sensitive" | 
/**  Production data, releases, anything touching equipment. */
"irreversible";

/**  A transition of one of the requester's Asks. */
export type StateChange = {
	/**  Position in the requester's event stream. */
	cursor: number,
	/**  The Ask that changed. */
	askId: string,
	/**  Its decision key. */
	decisionKey: string,
	/**  The state it entered. */
	state: AskState,
	/**  When it changed. */
	at: number,
};

/**  One entry in an Ask's trace. */
export type TraceEntry = {
	/**  Sortable id; trace order. */
	id: string,
	/**  What happened. */
	event: TraceEvent,
	/**  Requester-supplied references, such as `orca.run` or `branch`. */
	refs: { [key in string]: string },
	/**  Evidence link. */
	url: string | null,
	/**  Short explanation. */
	note: string | null,
	/**  When Roger recorded it. */
	at: number,
};

/**  An entry in the record of what happened after an answer. */
export type TraceEvent = 
/**  The requester first read the answer. Recorded by Roger. */
"delivered" | 
/**  The requester started work because of the answer. */
"dispatched" | 
/**  A step worth showing, such as a push. */
"progress" | 
/**  The requester acted on the answer. Terminal. */
"applied" | 
/**  The requester tried and failed. Terminal. */
"failed" | 
/**  The answer no longer applies. Terminal. */
"not_applicable" | 
/**
 *  Replaces the evidence link of the terminal event, which was wrong.
 *  Only after a terminal event; the original stays in the trace.
 */
"corrected";

/**  How quickly a person should see the Ask. Decides delivery. */
export type Urgency = 
/**  Push immediately, even in quiet hours. */
"now" | 
/**  Push after 30 working minutes. */
"soon" | 
/**  Inbox and daily digest. */
"later" | 
/**  Inbox only. */
"fyi";
